### PR TITLE
💥 Converted the project to TypeScript

### LINKED ISSUE #7: Convert this project to use TypeScript?
TypeScript is a great tool. I think we should convert it to use TypeScript to get rid of some errors. 
Assign it to me if you would like to convert it

### PR DESCRIPTION
**Pull request by max-programming**
Closes #7

I converted this project to use TypeScript. So far, everything is working fine. I changed the directory structure.
But I still need to check some more stuff so that nothing messes up in the end.

And the formatter in my IDE has formatted the code too.

### CODE REVIEW

**Comment by arturssmirnovs** [comment]
No worries, i will check on it and do work on it as well.. i will check this over weekend and will merge in pull request..

**Comment by max-programming** [comment]
> No worries, i will check on it and do work on it as well.. i will check this over weekend and will merge in pull request..

Yeah. I think you can check it better. Maybe you can clone [my branch](https://github.com/max-programming/parluks/tree/typescript-conversion) and then check it.

**Comment by arturssmirnovs** [comment]
Yes, i will do that ;)

**Comment by max-programming** [comment]
In these commits, I made the search bar better looking and more like how it works in the browser.
And I added icons to the context menu. Let me know your preference on the icons that I added. Which one looks better?
image
image

**Comment by arturssmirnovs** [comment]
Yeah, icons looks really good, I will inspect all code later today or tomorrow already

**Comment by arturssmirnovs** [comment]
@max-programming Really good job, code looks much cleaner now :rocket: :+1: :fire:

**Comment by arturssmirnovs** [comment]
I added you access to this repository ;) 
Think i will do some improvements in nearest month or so and we could launch version 1.1.. 

It's bit tricky to compile to linux / mac / windows files, so when more features add's up then i will create new version and try to advertise it on some forums.. 

This is cool tool :) Thanks for contributing!!! :heart:

**Comment by max-programming** [comment]
> I added you access to this repository ;) 
> Think i will do some improvements in nearest month or so and we could launch version 1.1.. 
> 
> It's bit tricky to compile to linux / mac / windows files, so when more features add's up then i will create new version and try to advertise it on some forums.. 
> 
> This is cool tool :) Thanks for contributing!!! :heart:  

Sure 😃. Thanks

**Pull request merged**
